#!/bin/bash

## check for gnome-keyring
KEYRING=`dpkg --get-selections |grep gnome-keyring`
if [ $? -eq 0 ]; then
    apt-get -y remove --purge gnome-keyring
fi

## check for spotify
SPOTIFY=`rgrep spotify /etc/apt/`
if [ $? -ne 0 ]; then
    apt-key adv –keyserver keyserver.ubuntu.com –recv-keys 94558F59
    add-apt-repository "deb http://repository.spotify.com stable non-free"
    apt-get update
fi
